# Generated by Django 3.1.12 on 2025-04-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormitoriesPlus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytracking',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_photos/'),
        ),
    ]
