# Generated by Django 3.1.12 on 2025-04-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DormitoriesPlus', '0003_auto_20250402_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='updated_at',
        ),
    ]
