# Generated by Django 3.1.12 on 2025-04-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormitoriesPlus', '0004_remove_building_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='הערות נוספות'),
        ),
    ]
