# Generated by Django 3.1.12 on 2025-04-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormitoriesPlus', '0006_add_request_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='הערות נוספות'),
        ),
    ]
