# Generated by Django 3.1.12 on 2025-04-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormitoriesPlus', '0008_auto_20250405_1911'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['user', 'request_type', 'status'], name='Dormitories_user_id_fa7066_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['room'], name='Dormitories_room_id_9fc143_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building'], name='Dormitories_buildin_7a2b51_idx'),
        ),
        migrations.AddIndex(
            model_name='roomassignment',
            index=models.Index(fields=['room'], name='Dormitories_room_id_083f50_idx'),
        ),
        migrations.AddIndex(
            model_name='roomassignment',
            index=models.Index(fields=['user'], name='Dormitories_user_id_415f20_idx'),
        ),
        migrations.AddIndex(
            model_name='roomassignment',
            index=models.Index(fields=['end_date'], name='Dormitories_end_dat_4cd2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='roomassignment',
            index=models.Index(fields=['start_date'], name='Dormitories_start_d_027ba8_idx'),
        ),
    ]
