# Generated by Django 5.2.1 on 2025-06-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormitoriesPlus', '0010_auto_20250407_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='building_name_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorytracking',
            name='item_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorytracking',
            name='item_name_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='content_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='admin_note_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='הערות מנהל'),
        ),
        migrations.AddField(
            model_name='request',
            name='admin_note_he',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='הערות מנהל'),
        ),
        migrations.AddField(
            model_name='request',
            name='fault_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='fault_description_he',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='fault_type_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='סוג התקלה'),
        ),
        migrations.AddField(
            model_name='request',
            name='fault_type_he',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='סוג התקלה'),
        ),
        migrations.AddField(
            model_name='request',
            name='note_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='הערות נוספות'),
        ),
        migrations.AddField(
            model_name='request',
            name='note_he',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='הערות נוספות'),
        ),
        migrations.AddField(
            model_name='request',
            name='urgency_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='דחיפות'),
        ),
        migrations.AddField(
            model_name='request',
            name='urgency_he',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='דחיפות'),
        ),
        migrations.AddField(
            model_name='room',
            name='notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='notes_he',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number_he',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventorytracking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roomassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
